stages:
  - build
  - deploy_to_stage


build-job:
  stage: build
  script:
    - echo $CI_PIPELINE_ID
    - docker build -t teamsoft_app:$CI_PIPELINE_ID .


deploy-prod:
  stage: deploy_to_stage
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."